// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqcOvSNPgRM2Fcf8EwC6mGlg-I2NJzpUs',
    appId: '1:810088496805:web:ba0fdcaebe30cc568d574c',
    messagingSenderId: '810088496805',
    projectId: 'roka-store-c938b',
    authDomain: 'roka-store-c938b.firebaseapp.com',
    storageBucket: 'roka-store-c938b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOo_eARtYudzg2JHmAhUvHzGCRAyZBuDU',
    appId: '1:810088496805:android:47e5bb39a5f5cb378d574c',
    messagingSenderId: '810088496805',
    projectId: 'roka-store-c938b',
    storageBucket: 'roka-store-c938b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz95AF4emT1SNlZWWSC8YP-hkC3Mna-YM',
    appId: '1:810088496805:ios:11c8e31b3894859c8d574c',
    messagingSenderId: '810088496805',
    projectId: 'roka-store-c938b',
    storageBucket: 'roka-store-c938b.appspot.com',
    iosClientId: '810088496805-llir0efs59ap83jrlmrdfk4imdrtj6oj.apps.googleusercontent.com',
    iosBundleId: 'com.abuarin.rokastore',
  );
}
